-----------------------------------------------------------
-- Exercise 15.4

fibs :: [Integer]
fibs = 0 : 1 : [x + y | (x, y) <- zip fibs (tail fibs)]

-----------------------------------------------------------

{-
  This definition constructs the Fibonacci sequence 
  starting with 0 and 1, followed by an infinite list 
  generated by summing pairs of previous elements. These 
  pairs are created using zip, which combines the fibs list 
  with its own tail. The list comprehension then adds each 
  pair (x, y) to produce the next element in the sequence.

  This definition works via lazy self-reference, meaning 
  the list refers to itself to generate new values, but 
  only computes elements as needed.

  Example:

    ghci> :l ex15-4.hs
    ghci> take 10 fibs
    [0,1,1,2,3,5,8,13,21,34]
-}