module Chapter_04.Ex4_27 where
import Library.Pictures

-----------------------------------------------------------
-- Exercise 4.27

-- | Builds a white n x n square with a black diagonal from 
-- top-left to bottom-right 
diagonal :: Integer -> Picture
diagonal n
  | n <= 0    = error "diagonal: non-positive size"
  | otherwise = rows 0
  where
    rows r
      | r == n - 1 = cols r 0     -- builds last row
      | otherwise  = cols r 0 `above` rows (r + 1) 
    cols r c 
      | c == n - 1 = if r == c then black else white  
      | c == r     = black `beside` cols r (c + 1) 
      | otherwise  = white `beside` cols r (c + 1) 


-- | Alternative solution for diagonal
diagonal' :: Integer -> Picture
diagonal' n
  | n <= 0    = error "diagonal': non-positive size"
  | otherwise = build n
  where
    build 1 = row 1
    build r = row r `above` build (r - 1)
    row r = padLeft (n - r) (padRight (r - 1) black)
    padLeft 0 p = p
    padLeft k p = white `beside` padLeft (k - 1) p
    padRight 0 p = p
    padRight k p = padRight (k - 1) p `beside` white


----------------------------------------------------------- 

{-

Testing in GHCi

ghci> :set -i..
ghci> :load Ex4_27
printPicture (diagonal 5)
######........................
######........................
######........................
######........................
######........................
######........................
......######..................
......######..................
......######..................
......######..................
......######..................
......######..................
............######............
............######............
............######............
............######............
............######............
............######............
..................######......
..................######......
..................######......
..................######......
..................######......
..................######......
........................######
........................######
........................######
........................######
........................######
........................######


-}