module Chapter_05.Ex5_23 where

-----------------------------------------------------------
-- Exercise 5.23

duplicate :: String -> Integer -> String
duplicate s n 
  | n <= 0    = ""
  | otherwise = concat [s | _ <- [1..n]]


-----------------------------------------------------------

{-

The generator in duplicate uses a wildcard because the 
values generated by [1..n] are ignored. The generator is in
fact only used as a counter to repeat the string exactly n
times.

Testing in GHCi

ghci> :l Ex5_23
ghci> putStrLn (duplicate "lol" 10)
lollollollollollollollollollol


-}
